### ISSUE TITLE
No module named 'reformer_pytorch'

### ISSUE THREAD

**Issue by lzb0854** [thuml/Autoformer#188]
Traceback (most recent call last):
  File "E:/时间序列预测/Autoformer-main/Autoformer-main/run.py", line 6, in <module>
    from exp.exp_main import Exp_Main
  File "E:\时间序列预测\Autoformer-main\Autoformer-main\exp\exp_main.py", line 9, in <module>
    from models import Informer, Autoformer, Transformer, Reformer
  File "E:\时间序列预测\Autoformer-main\Autoformer-main\models\Informer.py", line 8, in <module>
    from layers.SelfAttention_Family import FullAttention, ProbAttention, AttentionLayer
  File "E:\时间序列预测\Autoformer-main\Autoformer-main\layers\SelfAttention_Family.py", line 12, in <module>
    from reformer_pytorch import LSHSelfAttention
ModuleNotFoundError: No module named 'reformer_pytorch'

显示没有这个包，怎么解决呢

**Comment by wuhaixu2016** [comment]
你好，可以直接安装pip install reformer_pytorch
