### ISSUE TITLE
do_predict上的一些问题

### ISSUE THREAD

**Issue by kyrieLLL** [thuml/Autoformer#28]
在现实数据集上运行do_predict, autoformer模型能够顺利出结果，但是同样的参数设置下informer和transformer出现报错，如下：

> Traceback (most recent call last):
  File "run.py", line 121, in <module>
    exp.predict(setting, True)
  File "/share/home/luozicong/transformer-based model/Autoformer-main/exp/exp_main.py", line 311, in predict
    outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark)
  File "/share/home/luozicong/anaconda3/envs/transformer/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/share/home/luozicong/transformer-based model/Autoformer-main/models/Informer.py", line 74, in forward
    dec_out = self.dec_embedding(x_dec, x_mark_dec)
  File "/share/home/luozicong/anaconda3/envs/transformer/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/share/home/luozicong/transformer-based model/Autoformer-main/layers/Embed.py", line 117, in forward
    x = self.value_embedding(x) + self.temporal_embedding(x_mark) + self.position_embedding(x)
 RuntimeError:` The size of tensor a (48) must match the size of tensor b (96) at non-singleton dimension 1

**Comment by wuhaixu2016** [comment]
Hi, thanks for the reminder.

I have fixed this bug in the latest commit:
https://github.com/thuml/Autoformer/commit/d4da99dd50f58853de4483b7b0c6e416b89e9dc4
