### ISSUE TITLE
Training issue

### ISSUE THREAD

**Issue by Daniel-Jiang358** [thuml/Autoformer#60]
Hello, author Wu. Autoformer is a remarkble job, but I have some problems during training. 

Namespace(activation='gelu', batch_size=32, bucket_size=4, c_out=7, checkpoints='./checkpoints/', d_ff=2048, d_layers=1, d_model=512, data='total', data_path='total.csv', dec_in=7, des='test', devices='0,1,2,3', distil=True, do_predict=False, dropout=0.05, e_layers=2, embed='timeF', enc_in=7, factor=1, features='MS', freq='h', gpu=1, is_training=1, itr=2, label_len=48, learning_rate=0.0001, loss='mse', lradj='type1', model='Autoformer', model_id='test', moving_avg=25, n_hashes=4, n_heads=8, num_workers=10, output_attention=False, patience=3, pred_len=96, root_path='./data/ETT/', seq_len=96, target='SYSLoad', train_epochs=10, use_amp=False, use_gpu=True, use_multi_gpu=False)
Use GPU: cuda:1
>>>>>>>start training : test_Autoformer_total_ftMS_sl96_ll48_pl96_dm512_nh8_el2_dl1_df2048_fc1_ebtimeF_dtTrue_test_0>>>>>>>>>>>>>>>>>>>>>>>>>>
train 51939
val 7353
test 14799
Traceback (most recent call last):
  File "/data/jyq/Autoformer-main/Autoformer-main/run.py", line 116, in <module>
    exp.train(setting)
  File "/data/jyq/Autoformer-main/Autoformer-main/exp/exp_main.py", line 147, in train
    outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark, batch_y)
  File "/data/jyq/Anaconda3/envs/autoformer/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/jyq/Autoformer-main/Autoformer-main/models/Autoformer.py", line 87, in forward
    enc_out = self.enc_embedding(x_enc, x_mark_enc)
  File "/data/jyq/Anaconda3/envs/autoformer/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/jyq/Autoformer-main/Autoformer-main/layers/Embed.py", line 133, in forward
    x = self.value_embedding(x) + self.temporal_embedding(x_mark)
  File "/data/jyq/Anaconda3/envs/autoformer/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/jyq/Autoformer-main/Autoformer-main/layers/Embed.py", line 39, in forward
    x = self.tokenConv(x.permute(0, 2, 1)).transpose(1, 2)
  File "/data/jyq/Anaconda3/envs/autoformer/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/jyq/Anaconda3/envs/autoformer/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 298, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/data/jyq/Anaconda3/envs/autoformer/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 293, in _conv_forward
    _single(0), self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [512, 7, 3], expected input[32, 10, 98] to have 7 channels, but got 10 channels instead

I don't know where to set the channels. Thanks very much if you could give me an answer.

**Comment by Ink-Jiang** [comment]
[total.csv](https://github.com/thuml/Autoformer/files/8841845/total.csv)
Here is my datasets, Thanks

**Comment by Zero-coder** [comment]
The channel is likely to be the columns of your datasets,for example,in ETT,the data looks like this:
date,HUFL,HULL,MUFL,MULL,LUFL,LULL,OT,igoring the date column,the rest 7 columns is supposed to be the channel. 
I maybe wrong,btw,you are using your own datasets?Then you better to watch Custom_datasets.

**Comment by Daniel-Jiang358** [comment]
I see. I came out to find that set the enc_in, dec_in and c_out can solve the problem. Thanks for your kind reply.

**Comment by Zero-coder** [comment]
My pleasure.
