### ISSUE TITLE
how can i use multi gpu ?

### ISSUE THREAD

**Issue by bub3690** [thuml/Autoformer#76]
`python -u run.py --is_training 1 --root_path ./dataset/wspd/ --data_path T69_T90_wspd.csv --model_id "Wspd_720_576_T69_T90_2" --model Autoformer --data custom --features MS --freq 10min --embed fixed --seq_len 720 --label_len 576 --pred_len 288 --e_layers 2 --d_layers 1 --factor 3 --enc_in 8 --dec_in 8  --des 'Exp' --itr 1 --train_epochs 10 --num_workers 8 --batch_size 128 --target Wspd --c_out 8 --use_gpu True --use_multi_gpu --devices '0,1'`

----
# result

True
Args in experiment:
Namespace(activation='gelu', batch_size=128, bucket_size=4, c_out=8, checkpoints='./checkpoints/', d_ff=2048, d_layers=1, d_model=512, data='custom', data_path='T69_T90_wspd.csv', dec_in=8, des='Exp', device_ids=[0, 1], devices='0,1', distil=True, do_predict=False, dropout=0.05, dvices='0,1', e_layers=2, embed='fixed', enc_in=8, factor=3, features='MS', freq='10min', gpu=0, is_training=1, itr=1, label_len=576, learning_rate=0.0001, loss='mse', lradj='type1', model='Autoformer', model_id='Wspd_720_576_T69_T90_2', moving_avg=25, n_hashes=4, n_heads=8, num_workers=8, output_attention=False, patience=3, pred_len=288, root_path='./dataset/wspd/', seq_len=720, target='Wspd', train_epochs=10, use_amp=False, use_gpu=True, use_multi_gpu=True)
Use GPU: cuda:0
Traceback (most recent call last):
  File "run.py", line 158, in <module>
    main()
  File "run.py", line 120, in main
    exp = Exp(args)  # set experiments
  File "/shared/home/mai/jongbub/Autoformer/exp/exp_main.py", line 24, in __init__
    super(Exp_Main, self).__init__(args)
  File "/shared/home/mai/jongbub/Autoformer/exp/exp_basic.py", line 10, in __init__
    self.model = self._build_model().to(self.device)
  File "/shared/home/mai/anaconda3/envs/jongbub_torch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 927, in to
    return self._apply(convert)
  File "/shared/home/mai/anaconda3/envs/jongbub_torch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 579, in _apply
    module._apply(fn)
  File "/shared/home/mai/anaconda3/envs/jongbub_torch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 579, in _apply
    module._apply(fn)
  File "/shared/home/mai/anaconda3/envs/jongbub_torch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 579, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/shared/home/mai/anaconda3/envs/jongbub_torch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 602, in _apply
    param_applied = fn(param)
  File "/shared/home/mai/anaconda3/envs/jongbub_torch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 925, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable

----

why does 'RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable'  happen?

this is my nvidia-smi
![image](https://user-images.githubusercontent.com/30468434/181584864-1099bbd4-5e89-4b47-b830-d6aac8325ce1.png)

**Comment by LRQ577** [comment]
Have you solved your problem? I'm curious about the strategy you used to resolve the problem. Could you share the steps you took to address the problem?
